services:
  sshportal:
    build: ../../
    environment:
      - SSHPORTAL_DEFAULT_ADMIN_INVITE_TOKEN=integration
    command: server --debug
    depends_on:
      - testserver
    ports:
      - 2222

  testserver:
    build: ../../
    command: _test_server
    ports:
      - 2222

  client:
    build: .
    depends_on:
      - sshportal
      - testserver
    tty: true
