version: "3"

services:
  sshportal:
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
      - SSHPORTAL_DEFAULT_ADMIN_INVITE_TOKEN=integration
    command: server --debug
    depends_on:
      - testserver
    ports:
      - 2222

  testserver:
    build:
      context: ../../
      dockerfile: Dockerfile
    command: _test_server
    ports:
      - 2222

  client:
    build: .
    depends_on:
      - sshportal
      - testserver
    #volumes:
    #  - .:/integration
    tty: true
