version: 2

on:
  workflow_dispatch:

updates:

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  commit-message:
    prefix: "chore(deps)"
  groups:
    gh-actions:
      patterns:
        - "*"

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  commit-message:
    prefix: "chore(deps)"
  groups:
    go-deps:
      patterns:
        - "*"
