version: "2"

run:
  timeout: 2m
  tests: false

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - staticcheck
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
    - unused

  settings:
    goconst:
      min-len: 5
      min-occurrences: 4
    misspell:
      locale: US
    staticcheck:
      checks: ["all", "-QF1008", "-ST1000"]
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Fprint
