builds:
  - goos: [linux, darwin, windows]
    goarch: [386, amd64, arm64]
    ldflags:
      - -s -w -X main.GitSha={{.ShortCommit}} -X main.GitBranch=master -X main.GitTag={{.Version}}
archives:
  - wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  use: git
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^style:'
    - '^ci:'