name: CI
on:
  workflow_dispatch:
  push:
    paths:
      - "**.go"
      - "go.sum"
      - "go.mod"
      - "Dockerfile"
      - ".github/workflows/**"
      - ".golangci.yml"
  pull_request:
    paths:
      - "**.go"
      - "go.sum"
      - "go.mod"
      - "Dockerfile"
      - ".github/workflows/**"
      - ".golangci.yml"

permissions:
  contents: read
  pull-requests: read

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build the Docker image
        run: docker build . --file Dockerfile

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: latest

  unit-tests:
    needs: golangci-lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        run: go test ./... -timeout 30s
        continue-on-error: true
      - name: Run tests on Unix-like
        if: matrix.os != 'windows-latest'
        run: go test ./... -timeout 30s

  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.golang }}-
      - name: Run integ test with Docker compose
        run: cd ./examples/integration && make
